name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ubuntu Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libpcap-dev
      - name: Run Scripts
        run: |
          cd tests/
          make clean && make
          ./run-utests.sh
          cd ../fuzz
          make clean && CFLAGS="-DPL7M_USE_64K_PACKETS -DPL7M_ENABLE_ERROR" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_64K_PACKETS -DPL7M_USE_INTERNAL_FUZZER_MUTATE -DPL7M_ENABLE_ERROR" make
          ./run-fuzzer.sh
          make clean && CFLAGS="" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_INTERNAL_FUZZER_MUTATE" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_INTERNAL_FUZZER_MUTATE -DPL7M_USE_SIMPLEST_MUTATOR" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_SIMPLEST_MUTATOR" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_INTERNAL_FUZZER_MUTATE -DPL7M_USE_SIMPLEST_MUTATOR -DPL7M_USE_64K_PACKETS" make
          ./run-fuzzer.sh
          make clean && CFLAGS="-DPL7M_USE_SIMPLEST_MUTATOR -DPL7M_USE_64K_PACKETS" make
          ./run-fuzzer.sh
